services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streami
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - streami

  php:
    build:
      context: ./.devops/php
    ports:
      - "8000:8000"
    volumes:
      - .:/srv
    networks:
      - streami

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:

networks:
  streami:
